### ISSUE TITLE
Does not work in 1.12

### ISSUE THREAD

**Issue by Farsinuce** [MrDj200/noep#1]
Hi MrDj200,

My server (version 1.12) will not start when noep v1.0 installed.
Here is a logfile:
https://pastebin.com/8wV8r9d1

Forge version 14.21.1.2443

Kind regards,
Sinuce

**Comment by MrDj200** [comment]
Hey, First of all: Sry for the late answer, Github did not notify me :/

I pushed a new version yesterday.
Forgot to tell forge it is 1.12 compatible ^^

-Dj

**Comment by Farsinuce** [comment]
No problem. Thanks for looking into it :)
