### ISSUE TITLE
Suggestion: Add config option to disable log output enabled by default

### ISSUE THREAD

**Issue by ghost** [MrDj200/noep#2]
The output "Disabled enderman pickup of block:" for every block isn't really helpful to end users and increases log size/spam a fair bit which makes it difficult for a human to parse should there be an actual issue.  If you must include something, a simple "NoEndermenPickup: [Disabled/Prevented] Endermen pickup of X blocks" would be better in a default non verbose mode of operation.

**Comment by MrDj200** [comment]
Fixed with https://github.com/MrDj200/noep/commit/ad2493c595aaeaec211fb826ef6122662f9a552f


-Dj
